### ISSUE TITLE
Unify the MACH-Aero docs

### ISSUE THREAD

**Issue by nwu63** [mdolab/docs#38]
Currently, we have three separate repos:
- `MACH-Aero`
- `MACH-Aero-tutorial`
- `docs`

The information is scattered across these repos and it is confusing for newcomers to figure out what is needed to run MACH-Aero. I am proposing to merge the relevant information together, and create a single gateway for all MACH-Aero documentation (including both installation instructions and tutorials).
Specific steps are the follows:

1. ~~Deprecate `MACH-Aero`, as it is not serving much purpose at the moment~~ Leave the repo as-is, but update README to point to new site.
2. Make the `docs` repo the main repository, and rename to `MACH-Aero-docs`
3. Copy the content of the MACH-Aero README page to serve as the home page of this new repo. Update links and reorganize as needed.
4. Move the contents of `MACH-Aero-tutorial` into this repo, and organize the directories appropriately.
5. Move miscellaneous tutorials to private.
6. Host the resulting repo on readthedocs, and link to it from the MDO lab website.

## Type of issue
What types of issue is it?
_Select the appropriate type(s) that describe this issue_

- Documentation update

**Comment by nwu63** [comment]
As another note, it is also possible take advantage of the subprojects feature on readthedocs, and have everything for MACH-Aero under a single URL, with various subprojects. This has the advantage that everything is on the same URL/site, with a common side bar and search functionality.

**Comment by shamsheersc19** [comment]
Summarizing our offline discussion:
- Keep MACH-Aero because papers link to it.
- I'm in favor for consolidating docs and MACH-Aero-tutorial into a single repo because I confuse them all the time (I have a slight inclination towards keeping the MACH-Aero-tutorial name for this)
- Remove OAS and OpenConcept links from docs (they can be included in the Lab Guide instead)
- I'm in favor of moving the misc. tutorials to private-MACH-tutorial
